import { ProjectData } from "./types";

export const initialProject: ProjectData = {
  id: "proj-2026-imcc-042",
  name: "Autonomous High-Concurrency Distributed Event Orchestrator",
  description:
    "An enterprise-grade event-driven telemetry and microservice orchestration engine tailored for low-latency academic and industrial computing workloads with automated anomaly detection, sub-millisecond dispatching, and ISO-compliant audit logging.",
  type: "CAPSTONE",
  department: "Department of Computer Applications (MCA)",
  academicYear: "SY MCA (2nd Year)",
  division: "Division A",
  progressPercentage: 74,
  status: "Active",
  technologies: [
    "Next.js 15",
    "TypeScript",
    "Go",
    "Apache Kafka",
    "PostgreSQL",
    "Redis",
    "Docker",
    "Kubernetes",
    "TailwindCSS",
  ],
  objectives: [
    "Design asynchronous ingestion pipeline sustaining 50,000+ telemetry events/sec",
    "Implement zero-trust OAuth2 / JWT role-based institutional access control",
    "Construct interactive analytical dashboard with sub-second WebSocket telemetry",
    "Achieve >85% automated test coverage with CI/CD GitHub Actions workflow",
  ],
  repositoryUrl: "https://github.com/imcc-capstone/autonomous-orchestrator",
  figmaUrl: "https://figma.com/@imcc-design/system-architecture",
  miroUrl: "https://miro.com/app/board/capstone-milestone-architecture",
  teamMembers: [
    {
      id: "mem-1",
      name: "Aarav Sharma",
      role: "Team Lead",
      rollNumber: "2401098",
      email: "aarav.sharma@mesimcc.edu.in",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    },
    {
      id: "mem-2",
      name: "Ananya Deshmukh",
      role: "Full-Stack Dev",
      rollNumber: "2401104",
      email: "ananya.d@mesimcc.edu.in",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    },
    {
      id: "mem-3",
      name: "Rohan Kulkarni",
      role: "ML Engineer",
      rollNumber: "2401121",
      email: "rohan.k@mesimcc.edu.in",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    },
    {
      id: "mem-4",
      name: "Sneha Patil",
      role: "UI/UX Designer",
      rollNumber: "2401135",
      email: "sneha.p@mesimcc.edu.in",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80",
    },
  ],
  mentors: [
    {
      id: "men-1",
      name: "Dr. Shrikant Joshi",
      designation: "Associate Professor & Capstone Guide",
      department: "MCA & Data Engineering",
      email: "shrikant.joshi@mesimcc.edu.in",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    },
    {
      id: "men-2",
      name: "Vikram Sengupta",
      designation: "Staff Cloud Architect (Industry Mentor)",
      department: "Distributed Systems & Cloud",
      email: "v.sengupta@partner.skilli.in",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    },
  ],
  milestones: [
    {
      id: "m-1",
      name: "Problem Formulation & Synopsis Approval",
      phase: "Phase 1: Inception",
      description:
        "Submission of abstract, architectural feasibility study, comparative literature analysis, and tech stack approval from department committee.",
      startDate: "2026-08-01",
      dueDate: "2026-08-25",
      status: "COMPLETED",
      score: { obtained: 20, max: 20 },
      feedback:
        "Strong proposal with well-defined problem boundaries. Approved for development phase.",
      submissionFiles: [
        {
          name: "IMCC_MCA_Synopsis_Final_V2.pdf",
          size: "3.4 MB",
          url: "#",
          uploadedAt: "2026-08-24",
        },
      ],
    },
    {
      id: "m-2",
      name: "System Requirements Specification (SRS) & Architecture",
      phase: "Phase 2: Architectural Design",
      description:
        "Detailed ER diagrams, microservice schema contracts, UML sequence diagrams, and cloud infrastructure blueprint.",
      startDate: "2026-08-26",
      dueDate: "2026-09-15",
      status: "COMPLETED",
      score: { obtained: 24, max: 25 },
      feedback:
        "Clear modular architecture. Recommended caching Redis layer for frequent query lookups.",
      submissionFiles: [
        {
          name: "SRS_Specification_Doc_Approved.pdf",
          size: "5.8 MB",
          url: "#",
          uploadedAt: "2026-09-14",
        },
      ],
    },
    {
      id: "m-3",
      name: "Core Pipeline Implementation & Sprint Review 1",
      phase: "Phase 3: Core Implementation",
      description:
        "Implementation of Kafka consumer groups, distributed worker nodes, and telemetry logging endpoints with stress benchmark reports.",
      startDate: "2026-09-16",
      dueDate: "2026-10-05",
      status: "IN_REVIEW",
      feedback:
        "Review in progress by Dr. Shrikant Joshi. Pending live demonstration on Thursday at 2:00 PM.",
      submissionFiles: [
        {
          name: "Sprint1_Telemetry_Benchmark_Report.pdf",
          size: "8.2 MB",
          url: "#",
          uploadedAt: "2026-09-29",
        },
        {
          name: "Code_Quality_SonarQube_Scan.pdf",
          size: "1.1 MB",
          url: "#",
          uploadedAt: "2026-09-30",
        },
      ],
    },
    {
      id: "m-4",
      name: "Security Hardening, UI Dashboard & Integration",
      phase: "Phase 4: Integration & Security",
      description:
        "Frontend visualization cockpit, role-based JWT auth, rate limiting, vulnerability audit, and automated test suite.",
      startDate: "2026-10-06",
      dueDate: "2026-10-28",
      status: "IN_PROGRESS",
    },
    {
      id: "m-5",
      name: "Final Capstone Viva Voce & Thesis Defense",
      phase: "Phase 5: External Examination",
      description:
        "Comprehensive project demonstration before the university external examination committee and industry evaluators.",
      startDate: "2026-10-29",
      dueDate: "2026-11-20",
      status: "PENDING",
    },
  ],
  tasks: [
    {
      id: "t-1",
      title: "Deploy Kafka Cluster on Staging Kubernetes",
      description: "Provision 3-broker Strimzi Kafka operator with Persistent Volume Claims.",
      status: "DONE",
      priority: "HIGH",
      assignee: {
        id: "mem-3",
        name: "Rohan Kulkarni",
        role: "ML Engineer",
        rollNumber: "2401121",
        email: "rohan.k@mesimcc.edu.in",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
      },
      dueDate: "Sep 28",
      labels: ["DevOps", "Infrastructure"],
    },
    {
      id: "t-2",
      title: "Implement DPDP Compliant Data Masking",
      description: "Ensure PII attributes in telemetry events are salted and SHA-256 hashed.",
      status: "DONE",
      priority: "URGENT",
      assignee: {
        id: "mem-1",
        name: "Aarav Sharma",
        role: "Team Lead",
        rollNumber: "2401098",
        email: "aarav.sharma@mesimcc.edu.in",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
      },
      dueDate: "Sep 30",
      labels: ["Security", "Compliance"],
    },
    {
      id: "t-3",
      title: "Build Real-time WebSocket Telemetry Feed",
      description: "Socket.io streaming handler connecting Go dispatcher to Next.js client.",
      status: "IN_REVIEW",
      priority: "HIGH",
      assignee: {
        id: "mem-2",
        name: "Ananya Deshmukh",
        role: "Full-Stack Dev",
        rollNumber: "2401104",
        email: "ananya.d@mesimcc.edu.in",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
      },
      dueDate: "Oct 2",
      labels: ["API", "WebSockets"],
    },
    {
      id: "t-4",
      title: "Create Responsive Kanban & Evaluation UI",
      description: "Figma-matching interactive components with dark/light mode toggle.",
      status: "IN_PROGRESS",
      priority: "MEDIUM",
      assignee: {
        id: "mem-4",
        name: "Sneha Patil",
        role: "UI/UX Designer",
        rollNumber: "2401135",
        email: "sneha.p@mesimcc.edu.in",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80",
      },
      dueDate: "Oct 5",
      labels: ["Frontend", "Design"],
    },
    {
      id: "t-5",
      title: "Write End-to-End Stress Test Script",
      description: "k6 script simulating 5,000 concurrent client submissions to verify failover.",
      status: "TODO",
      priority: "MEDIUM",
      assignee: {
        id: "mem-3",
        name: "Rohan Kulkarni",
        role: "ML Engineer",
        rollNumber: "2401121",
        email: "rohan.k@mesimcc.edu.in",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
      },
      dueDate: "Oct 8",
      labels: ["QA", "Performance"],
    },
    {
      id: "t-6",
      title: "Automate Docker Multi-Arch Build Pipeline",
      description: "GitHub Actions workflow to produce multi-architecture container images.",
      status: "BACKLOG",
      priority: "LOW",
      assignee: {
        id: "mem-2",
        name: "Ananya Deshmukh",
        role: "Full-Stack Dev",
        rollNumber: "2401104",
        email: "ananya.d@mesimcc.edu.in",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
      },
      dueDate: "Oct 15",
      labels: ["CI/CD", "Docker"],
    },
  ],
  rubricCriteria: [
    {
      id: "c-1",
      title: "Problem Definition & Literature Survey",
      description:
        "Clarity of problem formulation, relevance to current computing paradigms, depth of peer-reviewed citations, and objective realism.",
      maxScore: 20,
      assignedScore: 19,
      weightage: "20%",
    },
    {
      id: "c-2",
      title: "System Architecture & Engineering Design",
      description:
        "Quality of architectural decomposition, modularity, data flow modeling, database normalization, and fault-tolerance guarantees.",
      maxScore: 25,
      assignedScore: 24,
      weightage: "25%",
    },
    {
      id: "c-3",
      title: "Implementation Depth & Code Quality",
      description:
        "Code modularity, idiomatic coding standards, git commit hygiene, clean asynchronous paradigms, and efficiency.",
      maxScore: 30,
      assignedScore: 26,
      weightage: "30%",
    },
    {
      id: "c-4",
      title: "Validation, Testing & Deployment",
      description:
        "Automated unit testing, integration tests, benchmark validation, Dockerization, and live production staging deployment.",
      maxScore: 15,
      assignedScore: 13,
      weightage: "15%",
    },
    {
      id: "c-5",
      title: "Viva Defense, Documentation & Presentation",
      description:
        "Clarity during Q&A interrogation, quality of formal LaTeX/IEEE report, and team collaboration synthesis.",
      maxScore: 10,
      assignedScore: 9,
      weightage: "10%",
    },
  ],
};

export const sampleDepartmentTeams = [
  {
    id: "proj-1",
    name: "Autonomous High-Concurrency Distributed Event Orchestrator",
    batch: "SY MCA - Div A",
    lead: "Aarav Sharma (2401098)",
    mentor: "Dr. Shrikant Joshi",
    progress: 74,
    status: "Active",
    lastSubmission: "Sprint 1 Benchmark Report",
    pendingAction: "Mentor Review Required",
  },
  {
    id: "proj-2",
    name: "AI-Powered Medical Diagnostic Assistant & DICOM Analyzer",
    batch: "SY MCA - Div B",
    lead: "Pooja Varma (2401142)",
    mentor: "Prof. Neha Ranade",
    progress: 88,
    status: "Active",
    lastSubmission: "Phase 3 Model Metrics",
    pendingAction: "Approved",
  },
  {
    id: "proj-3",
    name: "Zero-Knowledge Proof Identity Protocol for Universities",
    batch: "SY MCA - Div A",
    lead: "Kunal Mehra (2401087)",
    mentor: "Dr. Shrikant Joshi",
    progress: 60,
    status: "Active",
    lastSubmission: "Cryptographic Specification v1",
    pendingAction: "Needs Re-submission",
  },
  {
    id: "proj-4",
    name: "Edge-Computing Smart Campus Energy Optimization Engine",
    batch: "FY MCA - Div A",
    lead: "Tanvi Sane (2501015)",
    mentor: "Prof. Arvind Patil",
    progress: 42,
    status: "Active",
    lastSubmission: "Synopsis Proposal",
    pendingAction: "Synopsis Approved",
  },
];
